// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdovwkzopojjdupickri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkb3Z3a3pvcG9qamR1cGlja3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMzY3ODQsImV4cCI6MjA4NDcxMjc4NH0.EJbSgS8OVtlMBG2vCF3yQtmi5elgE3pqYNCxnUR7fVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});